// <auto-generated />
namespace LA_VENDUTA.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class auto : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(auto));
        
        string IMigrationMetadata.Id
        {
            get { return "202011121429028_auto"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
